utils: net: Add missing initialization of query_type
Fixes

In function ‘query_oob_port’,
    inlined from ‘main’ at ../utils/evl-net.c:483:3:
../utils/evl-net.c:157:24: error: ‘query_type’ may be used uninitialized [-Werror=maybe-uninitialized]
  157 |         if (!which || !*which) {
      |                        ^~~~~~
../utils/evl-net.c: In function ‘main’:
../utils/evl-net.c:371:18: note: ‘query_type’ was declared here
  371 |                 *query_type, *vlan_list = NULL;
      |                  ^~~~~~~~~~

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>